// The examples are demonstrations, not edits to the open project. Keep this
// catalog aligned with the controls actually exposed by My Exporter.
export const HELP_CATEGORIES = [
  { id: 'project', title: 'Projects & workspace' },
  { id: 'media', title: 'Media & source preview' },
  { id: 'timeline', title: 'Timeline & playback' },
  { id: 'clip', title: 'Picture & clip settings' },
  { id: 'audio', title: 'Audio & precise cuts' },
  { id: 'text', title: 'Titles & stickers' },
  { id: 'captions', title: 'Captions & languages' },
  { id: 'tools', title: 'Voice & extra tools' },
  { id: 'export', title: 'Export & finished videos' },
];

const targetFor = (category, overrides = {}) => ({
  panel: ['clip', 'audio'].includes(category) ? 'clip'
    : ['project', 'timeline', 'text', 'captions', 'tools', 'export'].includes(category) ? category : 'library',
  ...(category === 'media' ? { assetTab: 'Media' } : {}),
  ...overrides,
});

function topic(id, category, title, summary, location, steps, example, demoKind, options = {}) {
  return {
    id, category, title, summary, location, steps, example, demoKind,
    demoFrames: options.demoFrames || [
      { label: 'Find the control', note: steps[0] },
      { label: 'Try the action', note: steps[1] },
      { label: 'Example result', note: example },
    ],
    target: targetFor(category, { ...(id.startsWith('source-') ? { panel: 'source' } : {}), ...options.target }),
  };
}

export const HELP_TOPICS = [
  topic('project-save', 'project', 'Save & open a project',
    'Save an editable .pattanproject file so you can continue your work later.',
    'Top bar → Save / Open',
    ['Name your project in the top bar.', 'Click Save, choose a folder and save the .pattanproject file.', 'Click Open to load a saved project. Keep its original media files available.'],
    'Save “Wild Animals.pattanproject”, then reopen its timeline and settings.', 'project'),
  topic('project-new', 'project', 'New project',
    'Start an empty project in the current workspace.', 'Top bar → New',
    ['Save the current project if you want to keep it.', 'Click New and confirm clearing the current editor.', 'Import the media for your next video.'],
    'A new lesson starts with an empty timeline.', 'project'),
  topic('project-tabs', 'project', 'Project tabs',
    'Keep several projects open and switch between their editing workspaces.',
    'Timeline → More tools → New project tab',
    ['Choose New project tab from More tools.', 'Give the new project a name and add its media.', 'Click a project tab to switch; save each project to its own file.'],
    'Switch between “Wild Animals” and “Jingle Bells” projects.', 'project'),
  topic('project-autosave', 'project', 'Autosave & recovery',
    'Local autosave preserves the editing workspace; Save creates a portable project file.',
    'Project status / top bar → Save',
    ['Watch the autosave status while editing.', 'Use Save regularly for a .pattanproject copy.', 'If Save recovery copy appears, use it before opening or starting another project.'],
    'Save a recovery copy of preserved project data when recovery is requested.', 'project'),
  topic('project-history', 'project', 'Undo & Redo',
    'Step backward or forward through recorded editing changes.', 'Top bar → ↶ / ↷',
    ['Make an edit, such as removing an audio range.', 'Click ↶ or press Ctrl+Z to undo.', 'Click ↷ or press Ctrl+Y / Ctrl+Shift+Z to redo.'],
    'Undo restores both audio pieces and the sound between them.', 'organization'),
  topic('project-panels', 'project', 'Open & hide panels',
    'Show the library or settings when needed and give the preview more room.',
    'Navigation / Media › / ‹ Settings',
    ['Click Media, Audio or Titles to open that library.', 'Select a timeline item and click Clip settings to edit it.', 'Use Hide or Close to collapse the side panel; reopen it with the edge tabs.'],
    'Hide the library while checking the preview, then reopen Media.', 'organization'),
  topic('project-reset', 'project', 'Reset editor',
    'Clear loaded projects, media, edits and settings from the editor.',
    'Settings → Tools → Project tools → Reset editor',
    ['Save the projects you want to keep and wait for current jobs to finish.', 'Open Tools → Project tools and click Reset editor.', 'Read the confirmation before clearing the editor; saved files stay on your computer.'],
    'Reset returns the workspace to its default empty state.', 'project', { target: { panel: 'tools', section: 'Project tools' } }),
  topic('project-delete', 'project', 'Delete project',
    'Clear this project and delete its saved project file when one is attached.',
    'Settings → Tools → Project tools → Delete project',
    ['Save a separate copy if you may need the project later.', 'Click Delete project and read which project will be removed.', 'Confirm only when you want to remove that project file and clear its editor.'],
    'Delete “Practice.pattanproject” after keeping the final project.', 'project', { target: { panel: 'tools', section: 'Project tools' } }),

  topic('media-import', 'media', 'Import videos & images',
    'Bring local videos and images into the project library.', 'Media → + Import',
    ['Open Media and click + Import.', 'Choose one or several video or image files.', 'Use Preview to check a file or + Add to place it on the timeline.'],
    'Import Scene 1.mp4, Scene 2.mp4 and a cover image.', 'media'),
  topic('media-search', 'media', 'Search & filter media',
    'Find a library item by name or show only videos or images.',
    'Media / Audio → Search',
    ['Type part of a filename in Search media or Search audio.', 'In Media, choose All, Videos or Images.', 'Clear the search with × to show the library again.'],
    'Search “Scene 2” to find that scene quickly.', 'media'),
  topic('media-add', 'media', 'Add a library item',
    'Place a video, image or audio source into your edit.', 'Library card → + Add',
    ['Select a library item and preview it if needed.', 'Click + Add for the video or image you want next.', 'For audio, position the timeline playhead first, then click + Add.'],
    'Add a voice clip at the playhead position of 5 seconds.', 'media'),
  topic('media-auto-all', 'media', 'Add Auto All by scene number',
    'Add all imported videos and images in scene-number order.', 'Media → Add Auto All',
    ['Import your scenes with clear scene numbers in their names.', 'Click Add Auto All.', 'Review the ordered timeline; clips already present are not added again.'],
    'Scene 1, Scene 2, Scene 3 and Scene 10 appear in that order.', 'media', { demoFrames: [
      { label: 'Import numbered scenes', note: 'Scene 10 · Scene 3 · Scene 1 · Scene 2' },
      { label: 'Click Add Auto All', note: 'The editor reads the scene numbers.' },
      { label: 'Check the timeline', note: 'Scene 1 → Scene 2 → Scene 3 → Scene 10' },
    ] }),
  topic('media-remove', 'media', 'Remove from the library',
    'Remove a source card from the library while leaving its placed clips on the timeline.',
    'Library card → ×',
    ['Find the source card in Media or Audio.', 'Click × beside its name.', 'To remove a timeline clip as well, select that clip and use Delete.'],
    'Remove an unused source card; an existing placed clip stays in your edit.', 'media'),
  topic('source-range', 'media', 'Source In / Out',
    'Choose part of a video or audio source before inserting it.', 'Library card → Preview → Source',
    ['Click Preview on a source and scrub to its starting frame.', 'Click Mark In, then find its ending frame and click Mark Out; numeric In / Out also work.', 'Click Insert to timeline to add only that range.'],
    'In 2.000s and Out 6.000s insert four seconds of the source.', 'source', { demoFrames: [
      { label: 'Mark In', note: 'Source position 2.000s → Mark In' },
      { label: 'Mark Out', note: 'Source position 6.000s → Mark Out' },
      { label: 'Insert the range', note: 'The timeline receives the selected four seconds.' },
    ] }),
  topic('source-playback', 'media', 'Source playback & frame steps',
    'Inspect a source independently of the edited program preview.', 'Source → Play / frame buttons',
    ['Open a source with Preview.', 'Use Play / Pause or the source scrubber to inspect it.', 'Use Previous source frame / Next source frame to place In and Out carefully; × closes the source.'],
    'Step one source frame forward before marking Out.', 'source'),
  topic('source-image-duration', 'media', 'Image scene duration',
    'Set how long a still image appears when it is inserted.', 'Source image → Image duration',
    ['Preview an imported image.', 'Enter the desired Image duration in seconds.', 'Click Insert to timeline; you can adjust Duration later in Clip settings.'],
    'Show a cover image for 4 seconds.', 'source'),
  topic('media-templates', 'media', 'Project templates',
    'Apply Lesson, Vertical or Slideshow project settings to the current edit.',
    'Effects → Templates',
    ['Open Effects → Templates.', 'Choose Lesson, Vertical or Slideshow.', 'Review the canvas; Slideshow also adds fade-through-black transitions to image scenes.'],
    'Vertical changes the project to a 9:16 canvas at 30 fps.', 'organization', { target: { assetTab: 'Templates' } }),

  topic('timeline-playhead', 'timeline', 'Position the playhead',
    'The gold playhead marks the moment you are previewing or editing.',
    'Timeline ruler / gold scissors',
    ['Click or drag on the timeline ruler to seek.', 'Drag the gold scissors to position the playhead.', 'Use Left / Right for one-frame steps, or Home / End for the timeline boundaries.'],
    'Move the playhead to 3 seconds before splitting a clip.', 'timeline'),
  topic('timeline-playback', 'timeline', 'Play & preview modes',
    'Play the whole timeline or stop after the selected scene.', 'Preview → Play / Preview options',
    ['Click Play or press Space to play / pause.', 'Open Preview options and choose Play all scenes or Play selected scene only.', 'Pause and use the frame buttons to check a particular moment.'],
    'Play all scenes to check that narration continues correctly between scenes.', 'timeline'),
  topic('timeline-preview-view', 'timeline', 'Fullscreen, larger preview & guides',
    'Make the program preview easier to inspect.', 'Preview → Fullscreen / Preview options',
    ['Click Fullscreen; Esc or Exit fullscreen returns to the editor.', 'Use Preview options → Larger preview / Normal preview to change its space.', 'Use Show guides / Hide guides to check safe placement of text and logos.'],
    'Use fullscreen to check whether the caption text is comfortably readable.', 'organization'),
  topic('timeline-zoom', 'timeline', 'Zoom & expand the timeline',
    'See small timing differences or fit the entire edit on screen.', 'Timeline → Zoom / Fit / Expand timeline',
    ['Increase Zoom for detailed edits and use the timeline scroller to move across the edit.', 'Drag the scroller end knobs to change zoom, or click Fit to show the full timeline.', 'Click Expand timeline or a track-size arrow for more room; Restore preview returns the normal view.'],
    'Zoom in before adjusting a 0.250-second audio range.', 'organization'),
  topic('timeline-select', 'timeline', 'Select one or several scenes',
    'Choose the clips that the next editing action should affect.', 'Timeline → video / image clips',
    ['Click a scene to select it.', 'Ctrl+click another scene to add it to the selection.', 'Press Ctrl+A outside text fields to select all scenes.'],
    'Select Scenes 2 and 3 together before copying them.', 'timeline'),
  topic('timeline-reorder', 'timeline', 'Reorder scenes',
    'Change the order of scenes on the timeline.', 'Video clips → drag / right-click',
    ['Drag a video clip onto another clip to change its order.', 'Or right-click a scene and choose Move Earlier / Move Later.', 'Alt+Left / Alt+Right also moves the selected scene; review linked sound and captions afterward.'],
    'Move Scene 3 before Scene 2.', 'timeline'),
  topic('timeline-split', 'timeline', 'Split at playhead',
    'Divide a selected video, audio piece or caption at the playhead.', 'Timeline → Split / S',
    ['Select the item you want to split.', 'Put the playhead inside that item.', 'Click Split, click the positioned scissors or press S.'],
    'Split an eight-second clip at 3 seconds into two editable pieces.', 'timeline'),
  topic('timeline-copy', 'timeline', 'Copy, paste & duplicate scenes',
    'Reuse a selected scene or a group of selected scenes.', 'More tools / scene right-click menu',
    ['Select one or several scenes and press Ctrl+C.', 'Select the scene after which you want the copies, then press Ctrl+V.', 'Use Duplicate clip / Ctrl+D for a copy of the selected scene.'],
    'Copy an intro scene and paste it after the selected scene.', 'timeline'),
  topic('timeline-group', 'timeline', 'Group with next clip',
    'Mark two adjacent clips as a group while keeping their separate edits.', 'More tools → Group with next clip',
    ['Select a scene that has another scene immediately after it.', 'Choose Group with next clip, or right-click → Merge With Next.', 'Continue editing each clip separately; this does not render them into one media file.'],
    'Group Scenes 2 and 3 without flattening their trims or caption timing.', 'timeline'),
  topic('timeline-delete', 'timeline', 'Delete & Ripple editing',
    'Choose whether deletion leaves a gap or closes the deleted scene time.', 'Timeline → Ripple / Delete',
    ['Select a scene and turn Ripple off if its deleted time should remain empty.', 'Use Delete to remove it with the current Ripple setting.', 'Use Ripple delete or Shift+Delete to close its time and move later material earlier.'],
    'With Ripple off, deleting Scene 2 leaves its timeline time empty.', 'timeline'),
  topic('timeline-snap', 'timeline', 'Timeline snapping',
    'Let the playhead snap near clip edges, audio boundaries, captions and markers.', 'Timeline → Snap / N',
    ['Turn Snap on to help position the playhead near known boundaries.', 'Zoom in for closer positioning.', 'Turn Snap off or press N when you need to seek without snapping.'],
    'The playhead snaps to the start of Scene 2.', 'timeline'),
  topic('timeline-markers', 'timeline', 'Add, seek & delete markers',
    'Remember useful positions without changing the video.', 'More tools → Add marker / M',
    ['Move the playhead to a useful moment.', 'Choose Add marker or press M.', 'Click a marker label to return there; its × removes the marker.'],
    'Mark the beginning of the animal introduction.', 'timeline'),
  topic('timeline-locks', 'timeline', 'Track locks & visibility',
    'Protect tracks or temporarily mute the audio mix and captions.', 'Timeline → track header icons',
    ['Use the lock icon to protect Video, Audio mix or Captions from supported edits.', 'Use the Audio mix speaker icon to mute imported audio tracks and background music.', 'Use the Captions CC / eye icon to hide captions; hidden captions are also omitted from export.'],
    'Lock the video track while editing the detached narration.', 'organization'),
  topic('timeline-shortcuts', 'timeline', 'Keyboard shortcuts',
    'Use shortcuts when focus is outside an input, text box or open menu.', 'Editor keyboard',
    ['Space: play / pause; Left / Right: frame steps; Home / End: boundaries; M: marker.', 'S: split; N: Snap; F2: rename; Ctrl+C / V: copy / paste; Ctrl+D: duplicate scene.', 'Ctrl+S: save; Ctrl+Z / Y: undo / redo; Delete: selected item; I / O: audio range In / Out.', 'Press F1 to open the How to use guide and its sample demos.'],
    'Select audio, press I at its start and O at its end, then preview the selection.', 'organization'),

  topic('clip-picture', 'clip', 'Fit, rotation & flips',
    'Control how the selected video or image fits the canvas.', 'Clip settings → Picture',
    ['Select a scene and open Clip settings.', 'Choose Show full picture or Fill canvas.', 'Choose Rotation or Flip horizontal / Flip vertical and check the preview.'],
    'Fill canvas removes letterboxing by cropping the outer picture.', 'transform'),
  topic('clip-all-framing', 'clip', 'Set framing for all scenes',
    'Apply full-picture or fill framing across the current timeline.', 'More tools → Fill canvas / scene right-click',
    ['Use More tools → Fill canvas to set all scenes to fill.', 'Right-click a scene → Crop and Zoom — Fill also applies fill to all scenes.', 'Use Crop to Fit — Full Frame from that menu to return all scenes to full-picture framing.'],
    'Fill every scene for a vertical lesson, then inspect each crop.', 'transform'),
  topic('clip-timing', 'clip', 'Trim start & duration',
    'Choose the source portion used by a video, or the display time of an image.', 'Clip settings → Timing',
    ['Select a scene and open Timing.', 'For a video, set Start and Duration in source seconds; for an image, set Duration.', 'Or right-click → Trim Start to Playhead / Trim End to Playhead and review the timeline.'],
    'Start 2s and Duration 5s use the source from 2s through 7s.', 'source'),
  topic('clip-speed', 'clip', 'Video playback speed',
    'Change video speed and its resulting timeline length.', 'Clip settings → Timing → Playback speed',
    ['Select a video scene.', 'Set Playback speed between 0.25× and 4×.', 'Check the displayed Timeline length and preview picture, sound and captions together.'],
    'A 10-second source portion at 2× occupies 5 seconds on the timeline.', 'timeline'),
  topic('clip-sound', 'clip', 'Source audio volume & mute',
    'Adjust the sound still attached to the selected video.', 'Clip settings → Picture → Volume',
    ['Select a video that contains audio.', 'Move Volume to adjust its original sound.', 'Check Mute source audio to silence it, or Detach audio for independent sound editing.'],
    'Lower original narration to 50% while leaving other audio tracks unchanged.', 'audio'),
  topic('clip-transform', 'clip', 'Scale, position & opacity',
    'Resize, move or fade the selected picture using transform controls.', 'Clip settings → Animation',
    ['Open Animation for the selected scene.', 'Adjust Scale, Horizontal position, Vertical position or Opacity.', 'If keyframes already exist, these changes add a keyframe at the current playhead.'],
    'Scale 1.2× makes the picture larger; Opacity 0.5 makes it partially transparent.', 'transform'),
  topic('clip-keyframes', 'clip', 'Animate with keyframes',
    'Change scale, position and opacity over the selected clip’s timeline time.', 'Clip settings → Animation → Add keyframe',
    ['Position the playhead within the selected scene and click Add keyframe.', 'Move to another moment and change Scale, position or Opacity to add the next keyframe.', 'Play the clip; click a keyframe time to seek or × to delete it.'],
    'A keyframe at 0s uses Scale 1×; another at 2s uses 1.3× for a gradual zoom.', 'keyframes'),
  topic('clip-transition', 'clip', 'Cut & fade-through-black transitions',
    'Choose a direct cut or a fade through black between scenes.', 'Effects → Transitions / Clip settings → Transition',
    ['Select the scene to change.', 'Choose Cut / Fade to black in Effects → Transitions, or use the Transition setting.', 'For a fade, adjust Transition length and preview the scene boundary.'],
    'A 0.4-second fade darkens the picture near the boundary.', 'transform', { target: { section: 'Transition' } }),
  topic('clip-filters', 'clip', 'Filters & color correction',
    'Apply a color preset or adjust brightness, contrast and saturation.', 'Effects → Filters / Clip settings → Color correction',
    ['Select a video or image and choose Natural, Vivid, Cinematic, Soft or Mono.', 'Open Color correction for individual Brightness, Contrast and Saturation adjustments.', 'Use Natural to restore the preset’s neutral color settings.'],
    'Mono sets saturation to zero for a black-and-white picture.', 'transform', { target: { section: 'Color correction' } }),
  topic('clip-cleanup', 'clip', 'Audio cleanup on export',
    'Apply noise cleanup or loudness normalization to a video’s source sound during export.', 'Clip settings → Audio cleanup',
    ['Select a video with source audio.', 'Enable Noise cleanup on export and / or Loudness normalization on export.', 'Export and listen to the finished file; these processes are applied during export.'],
    'Normalize a quiet scene’s narration in the exported video.', 'audio', { target: { section: 'Audio cleanup' } }),
  topic('clip-organize', 'clip', 'Rename, color mark & disable a clip',
    'Keep scenes easy to identify or temporarily turn off a scene.', 'Scene right-click menu',
    ['Right-click a scene → Rename Clip, or select it and press F2.', 'Choose Change Clip Colour to cycle its timeline color mark.', 'Choose Disable Clip / Enable Clip to toggle it and check the preview.'],
    'Rename “Scene 4” to “Tiger” and give it a blue color mark.', 'organization'),
  topic('clip-replace', 'clip', 'Replace a clip',
    'Choose another local video for a scene, then regenerate captions for its new speech.', 'Scene right-click → Replace Clip',
    ['Select the scene to replace and choose Replace Clip.', 'Choose the replacement video and review its length and sound.', 'Regenerate captions; the old scene’s captions and linked detached audio are removed.'],
    'Replace an incorrect animal scene while keeping the rest of the edit.', 'media'),
  topic('clip-locate', 'clip', 'Locate source & match first frame',
    'Find the selected scene’s source or return to the first frame it uses.', 'Scene right-click menu',
    ['Choose Locate in Media Library to open the source in the library / Source preview.', 'Choose Match First Frame to seek the selected scene’s starting frame.', 'Use Edit Properties or double-click a video clip to open its settings.'],
    'Return to the first used frame of a trimmed tiger scene.', 'source'),

  topic('audio-import', 'audio', 'Import & mix audio',
    'Add narration, music or sound effects as independent audio lanes.', 'Audio → + Import / timeline → + Audio',
    ['Position the timeline playhead where the sound should begin.', 'Click + Import in Audio or + Audio on the timeline and choose local files.', 'Each sound gets a separate lane; overlapping sounds play together.'],
    'Add narration at 0s and a sound effect at 5s.', 'audio', { target: { panel: 'library', assetTab: 'Audio' } }),
  topic('audio-detach', 'audio', 'Detach audio from a video',
    'Move a video’s sound into an editable audio lane and mute its attached source sound.', 'Selected video → More tools → Detach audio',
    ['Select a video scene that has sound.', 'Choose Detach audio from More tools or the scene’s right-click menu.', 'Select the new audio lane to trim, split, mute or remove a range independently.'],
    'Keep the animal picture while editing only its narration.', 'audio'),
  topic('audio-move-trim', 'audio', 'Move & trim an audio clip',
    'Position an audio piece or shorten its source portion with edge handles.', 'Audio lane → clip body / edge handles',
    ['Drag the audio clip body to move its start on the timeline.', 'Drag its outer left or right trim handle to shorten or extend within the available source.', 'Use Select Audio Range when you want to remove a middle section instead.'],
    'Move a sound effect from 3s to 5s without moving the video.', 'audio'),
  topic('audio-range-select', 'audio', 'Select an exact audio range',
    'Mark the sound to preview or remove using timeline seconds.', 'Selected audio → Clip settings → Audio range',
    ['Click Select Audio Range, then drag across the waveform or click In and then Out.', 'Adjust the selection handles, or enter In / Out to 0.001 second and press Enter.', 'Set In / Out at playhead buttons or I / O mark the current playhead position.'],
    'In 2.000s and Out 4.000s select exactly two timeline seconds.', 'audio-gap'),
  topic('audio-remove-range', 'audio', 'Remove Selected Audio',
    'Remove the marked audio and leave a silent gap, keeping other timeline items in place.', 'Selected audio → Audio range → Remove Selected Audio',
    ['Select Audio Range and mark its In and Out positions.', 'Click Preview Selected Audio to check exactly which sound is selected.', 'Click Remove Selected Audio; use Undo if you need that sound back.'],
    'Remove 2.000–4.000s: left audio ends at 2s, right audio still begins at 4s.', 'audio-gap', { demoFrames: [
      { label: 'Mark the range', note: 'In 2.000s · Out 4.000s' },
      { label: 'Preview selected audio', note: 'Check the sound between those timeline times.' },
      { label: 'Remove and leave a gap', note: '0–2s audio | 2–4s silence | 4s onward audio. Video stays in place.' },
    ] }),
  topic('audio-range-preview', 'audio', 'Preview Selected Audio',
    'Audition only the selected sound with the audio clip’s playback speed.', 'Audio range → Preview Selected Audio',
    ['Mark a valid In / Out range on the selected audio clip.', 'Click Preview Selected Audio.', 'Playback stops at Out; Stop Selected Audio stops it sooner.'],
    'Audition a two-second selection before removing it.', 'audio'),
  topic('audio-split-trim', 'audio', 'Split or trim audio at the playhead',
    'Separate audio into pieces or keep only the side you need.', 'Selected audio → More audio edits / right-click',
    ['Put the playhead inside the selected audio piece.', 'Choose Split at playhead / S to keep both pieces.', 'Choose Trim start to playhead or Trim end to playhead to keep only the wanted side.'],
    'Trim start to 3s keeps the audio after 3s at its timeline position.', 'audio'),
  topic('audio-settings', 'audio', 'Audio volume, speed, fades & mute',
    'Adjust how the selected audio piece plays.', 'Selected audio → Clip settings',
    ['Adjust Volume or check Mute this track.', 'Set Speed between 0.25× and 4×; its timeline duration changes with speed.', 'Set Fade in / Fade out in timeline seconds and listen to the result.'],
    'Add a 0.5-second fade in and a 1-second fade out to music.', 'audio'),
  topic('audio-copy', 'audio', 'Copy, paste & duplicate audio',
    'Reuse an audio piece at another timeline position.', 'Audio right-click menu / Ctrl+C / Ctrl+V',
    ['Select audio and choose Copy Audio or press Ctrl+C.', 'Move the gold playhead, then choose Paste at Gold Stick / Ctrl+V; the copy stops at that scene’s border.', 'Duplicate After Clip places a copy after the selected audio piece.'],
    'Paste narration at 5s inside an eight-second scene; the copy ends by 8s.', 'audio'),
  topic('audio-reattach', 'audio', 'Reattach Audio to Video',
    'Reconnect edited detached audio to its original video scene.', 'Audio range / audio right-click → Reattach Audio to Video',
    ['Select an audio piece detached from a video scene.', 'Choose Reattach Audio to Video.', 'Unchanged sound may return to the source; edited pieces stay linked, including any removed gaps.'],
    'Reattach edited narration while keeping the silent 2–4s gap.', 'audio-gap'),
  topic('audio-delete', 'audio', 'Delete an entire audio clip',
    'Remove a whole piece; Ripple determines whether later audio lanes move earlier.', 'Audio piece → Delete / More audio edits',
    ['Use the clip’s Delete button for a whole piece; the Delete key removes an active range instead.', 'Turn Ripple off to keep other audio positions, or on to shift later audio pieces earlier.', 'Use Delete entire audio clip in More audio edits or right-click → Delete Audio as alternatives.'],
    'With Ripple off, delete a sound effect without shifting later narration.', 'audio'),
  topic('audio-background', 'audio', 'Background music',
    'Add a project-wide music bed with its own volume control.', 'Library → Background music',
    ['Open Background music below the library.', 'Click + Add music and choose an audio file.', 'Set Music volume; use Replace music or Remove when needed.'],
    'Keep the music quiet enough to hear the narration clearly.', 'audio', { target: { panel: 'library', assetTab: 'Audio', section: 'Background music' } }),

  topic('text-add', 'text', 'Add text & title presets',
    'Place a text overlay at the current playhead.', 'Titles library / Settings → Text → + Add Text',
    ['Add media and position the playhead where the title should appear.', 'Choose Title, Lower third, Chapter or Quote in Titles, or use + Add Text.', 'Select the title on its timeline lane and edit its wording in Text settings.'],
    'Add a Lower third reading “Tiger” when the tiger scene begins.', 'title'),
  topic('text-style', 'text', 'Text font, color, shape & size',
    'Style the selected title or sticker.', 'Settings → Text → selected overlay',
    ['Select an overlay on the Titles timeline lane.', 'Edit Text, Font, Color and Size.', 'Choose No shape, Box, Rounded pill or Badge, then adjust Opacity and 3D depth.'],
    'Use a white 48-point “Tiger” label in a readable box.', 'title'),
  topic('text-position', 'text', 'Move or delete a title',
    'Place an overlay on the picture or remove it from the edit.', 'Program preview / Settings → Text',
    ['Seek to a time when the title is visible.', 'Drag its text directly in the program preview to reposition it.', 'Use Delete Text or select its timeline item and press Delete to remove it.'],
    'Move an animal name away from the main picture detail.', 'title'),
  topic('text-stickers', 'text', 'Stickers',
    'Add a star, check, arrow or heart as an editable overlay.', 'Effects → Stickers',
    ['Position the playhead and open Effects → Stickers.', 'Choose Star, Check, Arrow or Heart.', 'Drag it in the preview and use Text settings for color, size and other styling.'],
    'Place an arrow near the animal being explained.', 'title', { target: { panel: 'library', assetTab: 'Stickers' } }),

  topic('captions-generate', 'captions', 'Generate & regenerate captions',
    'Create timed captions from narration in the timeline’s video scenes.', 'Captions → Automatic captions',
    ['Add videos with narration and choose Caption engine and Caption language.', 'Click Generate captions or Regenerate captions and wait for completion.', 'Review the text and timing before export; failed or cancelled generation preserves previous captions.'],
    'Generate speech captions for all enabled narrated scenes.', 'captions', { target: { section: 'Automatic captions' } }),
  topic('captions-engine', 'captions', 'Caption engine',
    'Choose local transcription or Groq cloud transcription.', 'Captions → Caption engine',
    ['Choose Local Whisper · offline for local transcription with its model installed.', 'Choose Groq · cloud transcription to use the configured Groq service and internet connection.', 'Generate captions, then review names and spelling before export.'],
    'Select Groq for an English narrated lesson, then review the transcript.', 'captions'),
  topic('captions-language', 'captions', 'Caption language & translation',
    'Choose the displayed caption language separately from the spoken language.', 'Captions → Caption language',
    ['Choose Same as spoken video / detect to keep the detected narration language.', 'Or choose English, Telugu, Hindi, Tamil, Kannada or Malayalam.', 'Generate captions and review translated words and timing against the narration.'],
    'English narration “tiger” should display Telugu “పులి”; verify it in review.', 'captions'),
  topic('captions-edit', 'captions', 'Edit caption text & timing',
    'Correct any caption and adjust when it appears.', 'Captions → Edit captions / Review captions',
    ['Click Edit captions to open the Complete Caption Timeline, or expand Review captions.', 'Correct the wording and set Start / End in timeline seconds.', 'In Review captions, press Edit Caption first and then Save; in the full editor, click Done when finished.'],
    'Correct an animal name and set its caption to match when the word is spoken.', 'captions'),
  topic('captions-delete-split', 'captions', 'Delete or split a caption',
    'Remove an unwanted line or divide one caption at the playhead.', 'Captions review / caption timeline item',
    ['Select the caption on the timeline or in Review captions.', 'Use its Delete button or press Delete to remove it.', 'For a split, put the playhead inside it and use Split / S, then review both resulting lines.'],
    'Delete a caption created from a background sound.', 'captions'),
  topic('captions-style', 'captions', 'Caption style, position & size',
    'Set the main appearance of captions in preview and export.', 'Captions → Caption style / Position / Text size',
    ['Choose Classic white, Readable black box, Cinema yellow or Karaoke highlight.', 'Choose Bottom, Middle or Top and adjust Text size.', 'Preview real captions; the familiar default is Arial at size 42.'],
    'Use a readable black box at the bottom with text size 42.', 'captions'),
  topic('captions-advanced', 'captions', 'Advanced caption font & proportions',
    'Customize caption font, boldness, color and text proportions.', 'Captions → Advanced caption options',
    ['Open Advanced caption options and choose Font style, Bold and Color.', 'Adjust Width and Height for the text proportions.', 'Review the preview before export; caption outlines are disabled.'],
    'Use Arial, bold white text, Width 100% and Height 100%.', 'captions', { target: { section: 'Advanced caption options' } }),
  topic('captions-wrap', 'captions', 'Caption line length',
    'Limit characters per line to make captions easier to read.', 'Captions → Line length',
    ['Move Line length between 16 and 60 characters.', 'Play a longer caption to check its wrapping.', 'Choose a length that fits your canvas and text size.'],
    'Reduce Line length for a narrow vertical video.', 'captions'),
  topic('captions-sample', 'captions', 'Caption sample preview',
    'Try caption styling before real captions exist.', 'Captions → Show Caption Sample',
    ['Before generating captions, click Show Caption Sample if the sample is hidden.', 'Adjust style, position, font and size using the sample.', 'Hide Caption Sample when finished; real generated captions replace the sample automatically.'],
    'Test size 42 and Bottom position without generating captions.', 'captions'),
  topic('captions-burn', 'captions', 'Permanent captions in export',
    'Choose whether captions become part of the exported video picture.', 'Captions → Show captions permanently in exported video',
    ['Enable Show captions permanently in exported video to burn visible captions into the MP4.', 'Check that the Captions track is visible and review real captions in the preview.', 'Use Export without captions when you want a clean export.'],
    'Export one captioned version and one clean version of the lesson.', 'captions'),
  topic('captions-cancel', 'captions', 'Cancel caption generation',
    'Stop the current transcription job while preserving existing captions.', 'Status bar / Settings → Cancel captions',
    ['While captions are generating, click Cancel captions or Cancel caption generation.', 'Wait for the operation to finish cancelling.', 'Review the preserved captions, adjust the engine or source and retry when ready.'],
    'Cancel a long caption run without deleting the previous reviewed captions.', 'captions'),

  topic('voice-translate', 'tools', 'Translate narration',
    'Replace a selected video’s narration with another language and voice.', 'Settings → Tools → Translate narration',
    ['Select a narrated video and choose the transcription engine in Captions.', 'Open Translate narration and choose Voice language and a male / female Narration voice.', 'Click Change Selected Video Voice, preview the result, then regenerate captions for the changed narration.'],
    'Replace an English animal narration with a consistent Telugu female voice.', 'voice', { target: { section: 'Translate narration' } }),
  topic('voice-morph', 'tools', 'Morph selected audio timbre',
    'Process the selected audio using the configured voice morphing service.', 'Settings → Tools → Voice tools',
    ['Select an audio piece on the timeline.', 'Choose Target voice timbre: SC3 Default Voice, Standard Female Voice or Standard Male Voice.', 'Click Morph Selected Audio Timbre and wait; listen to the result before export.'],
    'Apply the Standard Male Voice timbre to the selected narration track.', 'voice', { target: { section: 'Voice tools' } }),
  topic('voice-cancel', 'tools', 'Cancel current voice generation',
    'Use the available voice cancellation control during audio voice processing.', 'Settings → Cancel current voice generation',
    ['While the audio voice process is active, find Cancel current voice generation below Settings.', 'Click it and wait for the current operation to settle.', 'Check the status and selected audio before starting another operation.'],
    'Stop a voice-processing job before trying another target timbre.', 'voice'),
  topic('tools-stutters', 'tools', 'AI Stutter Cutter',
    'Review suspected fillers, repeated words and phrases using caption timings.', 'Tools → Audio & caption helpers → AI Stutter Cutter',
    ['Generate captions first, then open AI Stutter Cutter.', 'Use Listen on each suggestion to decide whether it is unwanted.', 'Use Cut This for one range or Auto Cut All for the reviewed suggestions; cuts close time across the timeline.'],
    'Listen to a detected “um”, then cut its time only if it is unnecessary.', 'timeline', { target: { section: 'Audio & caption helpers' } }),
  topic('tools-sfx', 'tools', 'Auto-Inject SFX',
    'Add generated sounds where caption text contains supported sound keywords.', 'Tools → Audio & caption helpers → Auto-Inject SFX',
    ['Generate or edit captions with [ding], [click], [whoosh], [cheer] or [typing] triggers.', 'Click Auto-Inject SFX.', 'Review the new audio lanes and adjust their volume, placement or delete unwanted sounds.'],
    'A [ding] trigger adds a ding track at that caption’s start.', 'audio', { target: { section: 'Audio & caption helpers' } }),
  topic('tools-chapters', 'tools', 'Generate Chapters',
    'Create chapter-title overlays from the scene names.', 'Tools → Audio & caption helpers → Generate Chapters',
    ['Add scenes, give them meaningful names and generate captions to enable the button.', 'Click Generate Chapters.', 'Review the chapter overlays on Titles and edit their wording and style in Text settings.'],
    'A scene named “Tiger” produces “Chapter 2: Tiger” at its scene start.', 'title', { target: { section: 'Audio & caption helpers' } }),
  topic('tools-logo', 'tools', 'Enable, import or remove a logo',
    'Show the Info Kids logo or a local image watermark over your video.', 'Settings → Tools → Logo & watermark',
    ['Click Enable Info Kids Logo, or Restore Info Kids Logo if it was removed.', 'To use another logo, Delete Logo first, then + Import another logo; transparent PNG / WebP works best.', 'Use Delete Logo to remove it, or toggle the enabled logo off.'],
    'Import your transparent school logo for the lesson.', 'title', { target: { section: 'Logo & watermark' } }),
  topic('tools-logo-position', 'tools', 'Logo position, size & opacity',
    'Place a watermark using presets or direct preview dragging.', 'Tools → Logo & watermark / program preview',
    ['Enable the logo, then choose Quick position such as Bottom right or Center.', 'Drag the logo in the preview to reposition it and drag its corner to resize.', 'Adjust Logo size and Opacity; Cover Flow Watermark applies a preset position that you can adjust.'],
    'Place the logo at bottom right at 16% size and 85% opacity.', 'transform', { target: { section: 'Logo & watermark' } }),
  topic('tools-crop', 'tools', 'Direct video crop',
    'Crop a local video directly without adding it to the editing timeline.', 'Tools → Direct crop & part export',
    ['Click Choose Large Video to Crop and choose the local file.', 'Adjust Left, Top, Crop width and Crop height while checking the crop rectangle.', 'Try Full, 4:3 Center or Square Center, then save the cropped video directly.'],
    'Use 4:3 Center to keep the middle 75% of the picture width.', 'crop', { target: { section: 'Direct crop & part export' } }),
  topic('tools-crop-parts', 'tools', 'Direct crop: export several parts',
    'Save one through ten chosen time ranges from the direct-crop source.', 'Tools → Direct crop & part export → How many parts?',
    ['Choose the crop source and set How many parts?.', 'For each part, use Mark START / END at Preview or enter Start / End seconds.', 'Choose Simultaneous saves, then Save All Parts and choose the output location.'],
    'Save Part 1 from 0–30s and Part 2 from 30–60s with the same crop.', 'crop', { target: { section: 'Direct crop & part export' } }),

  topic('export-settings', 'export', 'Canvas & aspect ratio',
    'Set the exported picture size and shape.', 'Settings → Export → Export settings',
    ['Choose Canvas: Full HD, 2K, 4K, Vertical or Square.', 'Choose Aspect ratio: 16:9, 9:16, 1:1 or 4:3.', 'Preview each scene and adjust its Fit if the new canvas changes the framing.'],
    'Choose Vertical and 9:16 for a portrait lesson.', 'export', { target: { section: 'Export settings' } }),
  topic('export-quality', 'export', 'Frame rate & quality',
    'Choose motion smoothness and the export quality / file-size balance.', 'Settings → Export → Frame rate / Quality',
    ['Choose 24, 30 or 60 fps in Frame rate.', 'Choose Maximum quality, Balanced or Smaller file.', 'Preview the edit, then export and inspect the finished file.'],
    '30 fps and Balanced are practical settings for a standard lesson video.', 'export'),
  topic('export-presets', 'export', 'Export presets',
    'Apply a ready-made combination of export settings.', 'Settings → Export → preset buttons',
    ['Choose YouTube 4K, Cinema, Shorts, Reels or 60 FPS.', 'Review Canvas, Aspect ratio, Frame rate and Quality after choosing the preset.', 'Adjust individual settings if your intended output needs another shape or size.'],
    'Shorts selects vertical 9:16, 30 fps and Balanced quality.', 'export'),
  topic('export-video', 'export', 'Export video',
    'Render the current timeline, sound, titles and enabled captions into an MP4.', 'Top bar → Export / Settings → Export video',
    ['Preview your edit and check the export settings.', 'Choose Export with current captions or Export video.', 'Choose the output folder and filename, then wait for Video ready.'],
    'Save the finished lesson as “Wild Animals.mp4”.', 'export'),
  topic('export-no-captions', 'export', 'Export without captions',
    'Save a video version that omits the caption overlay.', 'Export → Export without captions',
    ['Review the timeline and export settings.', 'Choose Export without captions.', 'Choose a separate filename to keep both versions. Titles and the enabled logo are still included.'],
    'Save “Wild Animals clean.mp4” alongside the captioned version.', 'export'),
  topic('export-generate', 'export', 'Generate captions & export',
    'Create new captions and then export them permanently in the video.', 'Export → Generate captions & export',
    ['Choose the caption engine, language and style.', 'Choose Generate captions & export.', 'After captions finish successfully, choose where to save the captioned MP4.'],
    'Generate Telugu captions and save the lesson with those captions.', 'export'),
  topic('export-progress', 'export', 'Progress, warnings & cancellation',
    'Follow the current export or stop that job safely.', 'Status bar / Settings → progress',
    ['Watch the phase, progress percentage and estimated remaining time.', 'If a warning appears, open Details and read it before retrying.', 'Use Cancel export to stop the current job, then wait until the editor becomes idle.'],
    'A media-path warning tells you which source needs attention before retrying.', 'export'),
  topic('export-result', 'export', 'Play the result & open its folder',
    'Inspect the completed video and find its saved file.', 'Video ready → Play video / Open folder',
    ['Wait until Video ready appears after a successful export.', 'Click Play video to inspect picture, narration, captions and audio gaps.', 'Click Open folder or Open exported file to locate the saved MP4.'],
    'Check that a removed 2–4s narration range is silent in the finished MP4.', 'export'),
  topic('export-shutdown', 'export', 'Generate, export & shut down',
    'Optionally schedule Windows shutdown after captions and export both succeed.', 'Tools → Audio & caption helpers → Generate captions, export & shut down',
    ['Save work in this app and other apps before selecting this command.', 'Read and confirm the shutdown warning, then let captions generate and choose the export filename.', 'After successful export, Windows shutdown is scheduled for 30 seconds later; failed export cancels this sequence.'],
    'Complete a long export, then shut down the computer after success.', 'export', { target: { panel: 'tools', section: 'Audio & caption helpers' } }),
];

export const HELP_DEFAULT_TOPICS = {
  projects: 'project-save', media: 'media-import', source: 'source-range',
  timeline: 'timeline-playhead', clip: 'clip-picture', audio: 'audio-import',
  audioRange: 'audio-remove-range', text: 'text-add', captions: 'captions-generate',
  tools: 'voice-translate', export: 'export-video',
};
