$f = 'D:\voice\script.js'
$c = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)

# Find and replace the current getLinearSyncFrame (sentence-snap version)
# with the correct typing-style version locked to audio clock

$oldFn = "// Sentence-sync for Chatterbox: reveal one complete sentence at a time,`r`n// locked to the audio clock. Each sentence appears the moment the voice reaches it.`r`nfunction getLinearSyncFrame(text, elapsedMs, durationMs) {`r`n  var safeText = String(text || '');`r`n  if (!safeText || !durationMs) {`r`n    return { displayedText: '', exactCharCountFloat: 0, mouthActive: false, speechElapsedMs: 0 };`r`n  }`r`n  var progress = elapsedMs >= durationMs ? 1 : (elapsedMs <= 0 ? 0 : elapsedMs / durationMs);`r`n  if (progress >= 1) {`r`n    return { displayedText: safeText, exactCharCountFloat: safeText.length, mouthActive: false, speechElapsedMs: elapsedMs };`r`n  }`r`n`r`n  // Character position the audio clock has reached`r`n  var charTarget = Math.floor(progress * safeText.length);`r`n`r`n  // Walk backwards from charTarget to find the last complete sentence boundary`r`n  // Boundaries: newline, bullet point start, or end of sentence (. ! ?)`r`n  var boundary = 0;`r`n  for (var i = 0; i <= charTarget && i < safeText.length; i++) {`r`n    var ch = safeText[i];`r`n    if (ch === '\n') {`r`n      // Newline boundary - include the newline`r`n      boundary = i + 1;`r`n    } else if (ch === '\u2022' && i > 0) {`r`n      // Bullet point - snap to just before it (previous boundary)`r`n      // Will be captured on next iteration when we see newline before it`r`n    } else if ((ch === '.' || ch === '!' || ch === '?') && i + 1 < safeText.length) {`r`n      var next = safeText[i + 1];`r`n      if (next === ' ' || next === '\n' || next === '\u2022') {`r`n        boundary = i + 2;`r`n      }`r`n    }`r`n  }`r`n`r`n  // Also check if charTarget itself lands after a sentence-ending punctuation`r`n  // to avoid holding back a finished sentence`r`n  var displayedText = boundary > 0 ? safeText.slice(0, boundary).trimEnd() : '';`r`n  var charFloat = boundary > 0 ? boundary : 0;`r`n`r`n  return {`r`n    displayedText: displayedText,`r`n    exactCharCountFloat: charFloat,`r`n    mouthActive: progress > 0 && progress < 1,`r`n    speechElapsedMs: elapsedMs`r`n  };`r`n}"

$newFn = "// Typing-style sync: characters reveal progressively as voice speaks,`r`n// locked 1:1 to audioElement.currentTime. At t/D progress, t/D of text is visible.`r`nfunction getLinearSyncFrame(text, elapsedMs, durationMs) {`r`n  var safeText = String(text || '');`r`n  if (!safeText || !durationMs) {`r`n    return { displayedText: '', exactCharCountFloat: 0, mouthActive: false, speechElapsedMs: 0 };`r`n  }`r`n  var progress = elapsedMs >= durationMs ? 1 : (elapsedMs <= 0 ? 0 : elapsedMs / durationMs);`r`n  if (progress >= 1) {`r`n    return { displayedText: safeText, exactCharCountFloat: safeText.length, mouthActive: false, speechElapsedMs: elapsedMs };`r`n  }`r`n`r`n  // Exact fractional character position driven by audio clock`r`n  var charFloat = progress * safeText.length;`r`n`r`n  // Snap to nearest word boundary so we never show half a word`r`n  var charIdx = Math.ceil(charFloat);`r`n  var displayedText;`r`n  if (charIdx >= safeText.length) {`r`n    displayedText = safeText;`r`n  } else {`r`n    // Find the end of the current word (next space after charIdx)`r`n    var nextSpace = safeText.indexOf(' ', charIdx);`r`n    var wordEnd = nextSpace >= 0 ? nextSpace : safeText.length;`r`n    // Only reveal up to the current word if we are past its midpoint`r`n    var prevSpace = safeText.lastIndexOf(' ', charIdx);`r`n    var wordStart = prevSpace >= 0 ? prevSpace + 1 : 0;`r`n    var wordMid = wordStart + (wordEnd - wordStart) * 0.3;`r`n    if (charIdx >= wordMid) {`r`n      // Past 30% of word - show the whole word`r`n      displayedText = safeText.slice(0, wordEnd);`r`n    } else {`r`n      // Not yet at word midpoint - show up to previous word`r`n      displayedText = prevSpace >= 0 ? safeText.slice(0, prevSpace) : '';`r`n    }`r`n  }`r`n`r`n  return {`r`n    displayedText: displayedText,`r`n    exactCharCountFloat: charFloat,`r`n    mouthActive: progress > 0 && progress < 1,`r`n    speechElapsedMs: elapsedMs`r`n  };`r`n}"

if ($c.Contains($oldFn)) {
    $c = $c.Replace($oldFn, $newFn)
    Write-Host "OK: typing-style sync restored"
} else {
    Write-Host "FAIL: old block not found exactly"
}

[System.IO.File]::WriteAllText($f, $c, [System.Text.Encoding]::UTF8)
Write-Host "Saved."
